[phases.setup]
nixPkgs = ["python37", "gcc", "postgresql_14"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn herbo_bueno.wsgi --log-file -"
