from django.core.management.base import BaseCommand
from vendors.models import Business
import uuid


class Command(BaseCommand):
    help = 'Populate the database with 10 sample businesses'

    def handle(self, *args, **options):
        businesses_data = [
            {
                'name': 'Green Valley Dispensary',
                'description': 'Premium cannabis dispensary offering high-quality products, expert consultation, and a welcoming atmosphere. We specialize in organic and locally-sourced products.',
                'category': 'wellness',
                'website': 'https://greenvalleydispensary.com',
                'email': 'info@greenvalleydispensary.com',
                'phone': '(555) 123-4567',
                'address': '1234 Main Street',
                'city': 'Los Angeles',
                'state': 'CA',
                'zip_code': '90210',
                'latitude': 34.0522,
                'longitude': -118.2437,
                'points_per_visit': 15,
                'has_golden_ticket': True,
                'hours_monday': '9:00 AM - 10:00 PM',
                'hours_tuesday': '9:00 AM - 10:00 PM',
                'hours_wednesday': '9:00 AM - 10:00 PM',
                'hours_thursday': '9:00 AM - 10:00 PM',
                'hours_friday': '9:00 AM - 11:00 PM',
                'hours_saturday': '9:00 AM - 11:00 PM',
                'hours_sunday': '10:00 AM - 9:00 PM',
            },
            {
                'name': 'Urban Threads Clothing Co.',
                'description': 'Trendy streetwear and urban fashion for the modern lifestyle. From casual wear to statement pieces, we curate the latest in urban fashion.',
                'category': 'clothing',
                'website': 'https://urbanthreads.com',
                'email': 'hello@urbanthreads.com',
                'phone': '(555) 234-5678',
                'address': '567 Fashion Avenue',
                'city': 'New York',
                'state': 'NY',
                'zip_code': '10001',
                'latitude': 40.7505,
                'longitude': -73.9934,
                'points_per_visit': 12,
                'has_golden_ticket': False,
                'hours_monday': '10:00 AM - 8:00 PM',
                'hours_tuesday': '10:00 AM - 8:00 PM',
                'hours_wednesday': '10:00 AM - 8:00 PM',
                'hours_thursday': '10:00 AM - 8:00 PM',
                'hours_friday': '10:00 AM - 9:00 PM',
                'hours_saturday': '10:00 AM - 9:00 PM',
                'hours_sunday': '11:00 AM - 7:00 PM',
            },
            {
                'name': 'Smoke & Mirrors Accessories',
                'description': 'Premium smoking accessories, glassware, and lifestyle products. We offer everything from high-end glass pieces to trendy accessories.',
                'category': 'paraphernalia',
                'website': 'https://smokeandmirrors.com',
                'email': 'contact@smokeandmirrors.com',
                'phone': '(555) 345-6789',
                'address': '890 Accessory Lane',
                'city': 'Denver',
                'state': 'CO',
                'zip_code': '80202',
                'latitude': 39.7392,
                'longitude': -104.9903,
                'points_per_visit': 18,
                'has_golden_ticket': True,
                'hours_monday': '11:00 AM - 9:00 PM',
                'hours_tuesday': '11:00 AM - 9:00 PM',
                'hours_wednesday': '11:00 AM - 9:00 PM',
                'hours_thursday': '11:00 AM - 9:00 PM',
                'hours_friday': '11:00 AM - 10:00 PM',
                'hours_saturday': '11:00 AM - 10:00 PM',
                'hours_sunday': '12:00 PM - 8:00 PM',
            },
            {
                'name': 'The Beat Lounge',
                'description': 'Underground music venue and bar featuring live performances, DJ sets, and craft cocktails. Experience the pulse of the city.',
                'category': 'entertainment',
                'website': 'https://thebeatlounge.com',
                'email': 'events@thebeatlounge.com',
                'phone': '(555) 456-7890',
                'address': '234 Music Street',
                'city': 'Miami',
                'state': 'FL',
                'zip_code': '33101',
                'latitude': 25.7617,
                'longitude': -80.1918,
                'points_per_visit': 20,
                'has_golden_ticket': False,
                'hours_monday': 'Closed',
                'hours_tuesday': '6:00 PM - 2:00 AM',
                'hours_wednesday': '6:00 PM - 2:00 AM',
                'hours_thursday': '6:00 PM - 2:00 AM',
                'hours_friday': '6:00 PM - 3:00 AM',
                'hours_saturday': '6:00 PM - 3:00 AM',
                'hours_sunday': '6:00 PM - 1:00 AM',
            },
            {
                'name': 'Zen Wellness Spa',
                'description': 'Holistic wellness center offering massage therapy, aromatherapy, meditation classes, and natural healing treatments.',
                'category': 'wellness',
                'website': 'https://zenwellnessspa.com',
                'email': 'relax@zenwellnessspa.com',
                'phone': '(555) 567-8901',
                'address': '456 Serenity Drive',
                'city': 'Portland',
                'state': 'OR',
                'zip_code': '97201',
                'latitude': 45.5152,
                'longitude': -122.6784,
                'points_per_visit': 14,
                'has_golden_ticket': False,
                'hours_monday': '9:00 AM - 7:00 PM',
                'hours_tuesday': '9:00 AM - 7:00 PM',
                'hours_wednesday': '9:00 AM - 7:00 PM',
                'hours_thursday': '9:00 AM - 7:00 PM',
                'hours_friday': '9:00 AM - 8:00 PM',
                'hours_saturday': '9:00 AM - 8:00 PM',
                'hours_sunday': '10:00 AM - 6:00 PM',
            },
            {
                'name': 'Artisan Coffee Roasters',
                'description': 'Specialty coffee shop featuring single-origin beans, artisanal brewing methods, and locally-sourced pastries. A coffee lover\'s paradise.',
                'category': 'food',
                'website': 'https://artisancoffee.com',
                'email': 'brew@artisancoffee.com',
                'phone': '(555) 678-9012',
                'address': '789 Coffee Corner',
                'city': 'Seattle',
                'state': 'WA',
                'zip_code': '98101',
                'latitude': 47.6062,
                'longitude': -122.3321,
                'points_per_visit': 10,
                'has_golden_ticket': False,
                'hours_monday': '6:00 AM - 6:00 PM',
                'hours_tuesday': '6:00 AM - 6:00 PM',
                'hours_wednesday': '6:00 AM - 6:00 PM',
                'hours_thursday': '6:00 AM - 6:00 PM',
                'hours_friday': '6:00 AM - 7:00 PM',
                'hours_saturday': '7:00 AM - 7:00 PM',
                'hours_sunday': '7:00 AM - 5:00 PM',
            },
            {
                'name': 'Tech Gadgets Hub',
                'description': 'Cutting-edge technology store featuring the latest gadgets, accessories, and tech innovations. From smartphones to smart home devices.',
                'category': 'retail',
                'website': 'https://techgadgetshub.com',
                'email': 'tech@techgadgetshub.com',
                'phone': '(555) 789-0123',
                'address': '321 Innovation Boulevard',
                'city': 'San Francisco',
                'state': 'CA',
                'zip_code': '94102',
                'latitude': 37.7749,
                'longitude': -122.4194,
                'points_per_visit': 16,
                'has_golden_ticket': True,
                'hours_monday': '10:00 AM - 8:00 PM',
                'hours_tuesday': '10:00 AM - 8:00 PM',
                'hours_wednesday': '10:00 AM - 8:00 PM',
                'hours_thursday': '10:00 AM - 8:00 PM',
                'hours_friday': '10:00 AM - 9:00 PM',
                'hours_saturday': '10:00 AM - 9:00 PM',
                'hours_sunday': '11:00 AM - 7:00 PM',
            },
            {
                'name': 'Vintage Vinyl Records',
                'description': 'Curated collection of vintage and rare vinyl records, turntables, and audio equipment. A haven for music collectors and audiophiles.',
                'category': 'retail',
                'website': 'https://vintagevinyl.com',
                'email': 'music@vintagevinyl.com',
                'phone': '(555) 890-1234',
                'address': '654 Music Row',
                'city': 'Nashville',
                'state': 'TN',
                'zip_code': '37201',
                'latitude': 36.1627,
                'longitude': -86.7816,
                'points_per_visit': 13,
                'has_golden_ticket': False,
                'hours_monday': '11:00 AM - 7:00 PM',
                'hours_tuesday': '11:00 AM - 7:00 PM',
                'hours_wednesday': '11:00 AM - 7:00 PM',
                'hours_thursday': '11:00 AM - 7:00 PM',
                'hours_friday': '11:00 AM - 8:00 PM',
                'hours_saturday': '11:00 AM - 8:00 PM',
                'hours_sunday': '12:00 PM - 6:00 PM',
            },
            {
                'name': 'Fitness First Gym',
                'description': 'State-of-the-art fitness center with modern equipment, personal training, group classes, and wellness programs for all fitness levels.',
                'category': 'wellness',
                'website': 'https://fitnessfirstgym.com',
                'email': 'train@fitnessfirstgym.com',
                'phone': '(555) 901-2345',
                'address': '987 Fitness Way',
                'city': 'Austin',
                'state': 'TX',
                'zip_code': '73301',
                'latitude': 30.2672,
                'longitude': -97.7431,
                'points_per_visit': 11,
                'has_golden_ticket': False,
                'hours_monday': '5:00 AM - 11:00 PM',
                'hours_tuesday': '5:00 AM - 11:00 PM',
                'hours_wednesday': '5:00 AM - 11:00 PM',
                'hours_thursday': '5:00 AM - 11:00 PM',
                'hours_friday': '5:00 AM - 11:00 PM',
                'hours_saturday': '6:00 AM - 10:00 PM',
                'hours_sunday': '7:00 AM - 9:00 PM',
            },
            {
                'name': 'Creative Studio & Gallery',
                'description': 'Art studio and gallery featuring local artists, workshops, and creative classes. A space for artistic expression and community building.',
                'category': 'entertainment',
                'website': 'https://creativestudiogallery.com',
                'email': 'art@creativestudiogallery.com',
                'phone': '(555) 012-3456',
                'address': '147 Art District',
                'city': 'Chicago',
                'state': 'IL',
                'zip_code': '60601',
                'latitude': 41.8781,
                'longitude': -87.6298,
                'points_per_visit': 17,
                'has_golden_ticket': True,
                'hours_monday': 'Closed',
                'hours_tuesday': '10:00 AM - 6:00 PM',
                'hours_wednesday': '10:00 AM - 6:00 PM',
                'hours_thursday': '10:00 AM - 6:00 PM',
                'hours_friday': '10:00 AM - 8:00 PM',
                'hours_saturday': '10:00 AM - 8:00 PM',
                'hours_sunday': '12:00 PM - 5:00 PM',
            }
        ]

        created_count = 0
        for business_data in businesses_data:
            business, created = Business.objects.get_or_create(
                name=business_data['name'],
                defaults=business_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'Created business: {business.name}')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'Business already exists: {business.name}')
                )

        self.stdout.write(
            self.style.SUCCESS(f'Successfully created {created_count} new businesses!')
        )
