# Generated by Django 3.2.25 on 2025-09-14 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_auto_20250914_0655'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('clothing', 'Clothing & Fashion'), ('paraphernalia', 'Paraphernalia & Accessories'), ('entertainment', 'Entertainment & Events'), ('food', 'Food & Beverage'), ('wellness', 'Wellness & Health'), ('retail', 'Retail & Shopping'), ('services', 'Services'), ('other', 'Other')], max_length=50)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='business_banners/')),
                ('qr_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('points_per_visit', models.PositiveIntegerField(default=10)),
                ('has_golden_ticket', models.BooleanField(default=False)),
                ('hours_monday', models.CharField(blank=True, max_length=50)),
                ('hours_tuesday', models.CharField(blank=True, max_length=50)),
                ('hours_wednesday', models.CharField(blank=True, max_length=50)),
                ('hours_thursday', models.CharField(blank=True, max_length=50)),
                ('hours_friday', models.CharField(blank=True, max_length=50)),
                ('hours_saturday', models.CharField(blank=True, max_length=50)),
                ('hours_sunday', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.PositiveIntegerField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('is_golden_ticket', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'business', 'scan_date')},
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('giveaway_entries', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VendorProduct',
        ),
    ]
