# Generated by Django 3.2.25 on 2025-09-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('giveaway_type', models.CharField(choices=[('vacation', 'Vacation Package'), ('vendor_prize', 'Vendor Prize')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('max_entries', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('destination', models.CharField(choices=[('caribbean', 'Caribbean'), ('europe', 'Europe'), ('asia', 'Asia'), ('north_america', 'North America'), ('south_america', 'South America'), ('africa', 'Africa'), ('oceania', 'Oceania')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('duration_days', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='vacation_images/')),
                ('includes', models.TextField(help_text="What's included in the package")),
                ('terms_conditions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prize_type', models.CharField(choices=[('clothing', 'Clothing'), ('paraphernalia', 'Paraphernalia'), ('concert_tickets', 'Concert Tickets'), ('vip_access', 'VIP Access'), ('gift_card', 'Gift Card'), ('other', 'Other')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='prize_images/')),
                ('quantity_available', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='GiveawayWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_date', models.DateTimeField(auto_now_add=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_date', models.DateTimeField(blank=True, null=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaways.giveaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='giveaway',
            name='vacation_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giveaways.vacationpackage'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='vendor_prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giveaways.vendorprize'),
        ),
        migrations.CreateModel(
            name='GiveawayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entries_count', models.PositiveIntegerField(default=1)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaways.giveaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'giveaway')},
            },
        ),
    ]
