# Generated by Django 3.2.25 on 2025-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prize_type', models.CharField(choices=[('clothing', 'Clothing'), ('paraphernalia', 'Paraphernalia'), ('concert_tickets', 'Concert Tickets'), ('vip_access', 'VIP Access'), ('gift_card', 'Gift Card'), ('other', 'Other')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='prize_images/')),
                ('quantity_available', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='vendor_prize',
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='giveaway_type',
            field=models.CharField(choices=[('vacation', 'Vacation Package'), ('business_prize', 'Business Prize')], max_length=50),
        ),
        migrations.DeleteModel(
            name='VendorPrize',
        ),
    ]
