# Generated by Django 3.2.25 on 2025-09-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_auto_20250914_0655'),
        ('vendors', '0002_auto_20250914_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprize',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.business'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='business_prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giveaways.businessprize'),
        ),
    ]
